// Friends Profile Data

export const FriendsProfileData = [
    {
        name: 'Bolu_Teephe',
        accountName: 'BoluTech',
        profileImage: require('../../storage/images/image1.jpg'),
        posts: 56,
        followers: 6575,
        following: 42,
        follow: false,
    },{
        name: 'Comfort_oye',
        accountName: 'Bolu Teephe',
        profileImage: require('../../storage/images/image2.jpg'),
        posts: 80,
        followers: 2675,
        following: 30,
        follow: false,
    },{
        name: 'Crazy_Tech',
        accountName: 'Tech',
        profileImage: require('../../storage/images/image3.jpeg'),
        posts: 40,
        followers: 4000,
        following: 70,
        follow: false,
    },{
        name: 'the_jerry',
        accountName: 'The Jerry',
        profileImage: require('../../storage/images/image4.jpg'),
        posts: 86,
        followers: 8000,
        following: 49,
        follow: false,
    },{
        name: 'The_Tom',
        accountName: 'The Tom',
        profileImage: require('../../storage/images/image5.jpg'),
        posts: 56,
        followers: 5674,
        following: 80,
        follow: false,
    },{
        name: 'Love_J',
        accountName: 'love_j',
        profileImage: require('../../storage/images/image6.jpeg'),
        posts: 10,
        followers: 9000,
        following: 20,
        follow: false,
    },{
        name: 'Elon_Musk',
        accountName: 'Elon',
        profileImage: require('../../storage/images/image7.jpg'),
        posts: 99,
        followers: 9987,
        following: 18,
        follow: false,
    },{
        name: 'Bill_Gate',
        accountName: 'Bill gate',
        profileImage: require('../../storage/images/post1.jpg'),
        posts: 18,
        followers: 4983,
        following: 90,
        follow: false,
    },{
        name: 'Anike_Ade',
        accountName: 'Anike Ade',
        profileImage: require('../../storage/images/post2.jpeg'),
        posts: 79,
        followers: 7895,
        following: 90,
        follow: false,
    },{
        name: 'Bro_Josh',
        accountName: 'Bro Josh',
        profileImage: require('../../storage/images/post3.jpg'),
        posts: 75,
        followers: 3245,
        following: 89,
        follow: false,
    },{
        name: 'Mark_Zuck',
        accountName: 'Zuckerberg',
        profileImage: require('../../storage/images/post4.jpg'),
        posts: 87,
        followers: 8998,
        following: 87,
        follow: false,
    },{
        name: 'Ben_Carson',
        accountName: 'ben carson',
        profileImage: require('../../storage/images/post5.jpg'),
        posts: 40,
        followers: 7987,
        following: 56,
        follow: false,
    },{
        name: 'Nelson_Mandela',
        accountName: 'nelson mandela',
        profileImage: require('../../storage/images/post1.jpg'),
        posts: 56,
        followers: 9766,
        following: 35,
        follow: false,
    },
    
]